source 'https://rubygems.org'

gem 'httparty'
gem 'nokogiri'
gem 'rails', '4.0.0'
gem 'sqlite3'

gem 'bootstrap-sass', '~> 2.3.2.1'
gem 'coffee-rails', '~> 4.0.0'
gem 'ejs'
gem 'flat-ui-rails', '~> 0.0.2'
gem 'jquery-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
